// Stubs for WebKit debug/inspector symbols missing from iOS JSCOnly Release build.
// This file must NOT use the precompiled header to avoid class redefinitions.
// All symbols use exact Itanium ABI mangled names generated by the compiler.

#include <cstdlib>
#include <cstddef>
#include <cstring>

extern "C" {

// === WTF debug stubs ===

// WTF::Detail::wtfStringCopyCount
int _ZN3WTF6Detail18wtfStringCopyCountE = 0;

// WTF::RefTracker::reportDead(void*)
void _ZN3WTF10RefTracker10reportDeadEPv(void*) {}

// WTF::RefTracker::reportLive(void*)
void _ZN3WTF10RefTracker10reportLiveEPv(void*) {}

// WTF::AtomStringImpl::isInAtomStringTable(WTF::StringImpl*)
bool _ZN3WTF14AtomStringImpl19isInAtomStringTableEPNS_10StringImplE(void*) { return true; }



// === bmalloc stubs ===

struct BmallocMemoryStatus { double a; double b; };
BmallocMemoryStatus _ZN7bmalloc12memoryStatusEv() { return { 0.5, 0 }; }

// === JSC debug assertion stubs ===

// JSC::AssertNoGC::s_scopeReentryCount
unsigned _ZN3JSC10AssertNoGC19s_scopeReentryCountE = 0;

// JSC::DFG::DoesGCCheck::verifyCanGC(VM&)
void _ZN3JSC3DFG11DoesGCCheck11verifyCanGCERNS_2VME(void*) {}

// JSC::ExceptionScope::unexpectedExceptionMessage()
const char* _ZN3JSC14ExceptionScope26unexpectedExceptionMessageEv() {
    return "Unexpected exception (iOS stub)";
}

// JSC::ThrowScope::ThrowScope(VM&, ExceptionEventLocation)
void _ZN3JSC10ThrowScopeC1ERNS_2VMENS_22ExceptionEventLocationE(void*, void*, ...) {}
void _ZN3JSC10ThrowScopeC2ERNS_2VMENS_22ExceptionEventLocationE(void*, void*, ...) {}

// JSC::ThrowScope::~ThrowScope()
void _ZN3JSC10ThrowScopeD1Ev(void*) {}
void _ZN3JSC10ThrowScopeD2Ev(void*) {}

// JSC::ThrowScope::throwException(JSGlobalObject*, Exception*)
void _ZN3JSC10ThrowScope14throwExceptionEPNS_14JSGlobalObjectEPNS_9ExceptionE(void*, void*, void*) {
    __builtin_trap();
}

// JSC::ThrowScope::throwException(JSGlobalObject*, JSValue)
void _ZN3JSC10ThrowScope14throwExceptionEPNS_14JSGlobalObjectENS_7JSValueE(void*, void*, long long) {
    __builtin_trap();
}

// JSC::TopExceptionScope::TopExceptionScope(VM&, ExceptionEventLocation)
void _ZN3JSC17TopExceptionScopeC1ERNS_2VMENS_22ExceptionEventLocationE(void*, void*, ...) {}
void _ZN3JSC17TopExceptionScopeC2ERNS_2VMENS_22ExceptionEventLocationE(void*, void*, ...) {}

// JSC::TopExceptionScope::~TopExceptionScope()
void _ZN3JSC17TopExceptionScopeD1Ev(void*) {}
void _ZN3JSC17TopExceptionScopeD2Ev(void*) {}

// JSC::ObjectInitializationScope::ObjectInitializationScope(VM&)
void _ZN3JSC25ObjectInitializationScopeC1ERNS_2VME(void*, void*) {}
void _ZN3JSC25ObjectInitializationScopeC2ERNS_2VME(void*, void*) {}

// JSC::ObjectInitializationScope::~ObjectInitializationScope()
void _ZN3JSC25ObjectInitializationScopeD1Ev(void*) {}
void _ZN3JSC25ObjectInitializationScopeD2Ev(void*) {}

// JSC::HandleSet::isLiveNode(HandleNode*)
bool _ZN3JSC9HandleSet10isLiveNodeEPNS_10HandleNodeE(void*) { return true; }

// JSC::MarkedBlock::assertMarksNotStale()
void _ZN3JSC11MarkedBlock19assertMarksNotStaleEv(void*) {}

// JSC::JSFunction::finishCreation(VM&)
void _ZN3JSC10JSFunction14finishCreationERNS_2VME(void*, void*) {}

// JSC::RegExpObject::finishCreation(VM&)
void _ZN3JSC12RegExpObject14finishCreationERNS_2VME(void*, void*) {}

// JSC::StrongRefTracker::refTrackerSingleton()
static char dummyStrongRefTracker[64];
void* _ZN3JSC16StrongRefTracker19refTrackerSingletonEv() { return dummyStrongRefTracker; }

// === JIT stubs (no JIT on iOS) ===

// JSC::JIT::compileSync(VM&, CodeBlock*, JITCompilationEffort)
void* _ZN3JSC3JIT11compileSyncERNS_2VMEPNS_9CodeBlockENS_20JITCompilationEffortE(void*, void*, int) {
    return nullptr;
}

// JSC::JIT::totalCompileTime()
double _ZN3JSC3JIT16totalCompileTimeEv() { return 0; }

// JSC::performJITMemcpy<ConstexprOptionSet<RepatchingFlag>{}>(void*, void const*, unsigned long)
void* _ZN3JSC16performJITMemcpyIXtlN3WTF18ConstexprOptionSetINS_14RepatchingFlagEEEEEEEPvS5_PKvm(
    void* dst, const void* src, unsigned long n) {
    return __builtin_memcpy(dst, src, n);
}

// === Inspector stubs ===

// Inspector::RemoteInspectionTarget dtor/methods
void _ZN9Inspector22RemoteInspectionTargetD2Ev(void*) {}
void _ZN9Inspector22RemoteInspectionTargetD1Ev(void*) {}
void _ZN9Inspector22RemoteInspectionTargetD0Ev(void*) {}
bool _ZNK9Inspector22RemoteInspectionTarget20remoteControlAllowedEv(void*) { return false; }
void _ZN9Inspector22RemoteInspectionTarget14setInspectableEb(void*, bool) {}

// Inspector::RemoteControllableTarget::init()
void _ZN9Inspector24RemoteControllableTarget4initEv(void*) {}

// Inspector::RemoteInspectorServer
static char dummyRemoteInspectorServer[64];
void* _ZN9Inspector21RemoteInspectorServer9singletonEv() { return dummyRemoteInspectorServer; }
void _ZN9Inspector21RemoteInspectorServer5startEPKct(void*, const char*, unsigned short) {}

// Inspector::JSGlobalObjectInspectorController
void _ZN9Inspector33JSGlobalObjectInspectorController22registerAlternateAgentEON3WTF9UniqueRefINS_18InspectorAgentBaseEEE(void*, void*) {}

// JSC::JSGlobalObject::inspectorController() const
static char dummyInspectorController[256];
void* _ZNK3JSC14JSGlobalObject19inspectorControllerEv(void*) { return dummyInspectorController; }

// JSC::JSGlobalObjectDebuggable
void _ZN3JSC24JSGlobalObjectDebuggableC2ERNS_14JSGlobalObjectE(void*, void*) {}
void _ZN3JSC24JSGlobalObjectDebuggableC1ERNS_14JSGlobalObjectE(void*, void*) {}
const void* _ZNK3JSC24JSGlobalObjectDebuggable4nameEv(void*) { return "BunGlobal"; }
void _ZN3JSC24JSGlobalObjectDebuggable7connectERN9Inspector15FrontendChannelEbb(void*, void*, bool, bool) {}
void _ZN3JSC24JSGlobalObjectDebuggable10disconnectERN9Inspector15FrontendChannelE(void*, void*) {}
void _ZN3JSC24JSGlobalObjectDebuggable25dispatchMessageFromRemoteEON3WTF6StringE(void*, void*) {}

} // extern "C"
