// Stubs for WebKit symbols that exist in debug/assertion builds but are
// stripped from the iOS Release JSCOnly build. Also stubs for JIT symbols
// since iOS has no JIT.
//
// This file must NOT use the precompiled header to avoid class redefinitions.
// All symbols use exact Itanium ABI mangled names generated by the compiler.

#include <cstdlib>
#include <cstddef>
#include <cstring>

extern "C" {

// === WTF debug stubs ===

int _ZN3WTF6Detail18wtfStringCopyCountE = 0;
void _ZN3WTF10RefTracker10reportDeadEPv(void*) {}
void _ZN3WTF10RefTracker10reportLiveEPv(void*) {}
bool _ZN3WTF14AtomStringImpl19isInAtomStringTableEPNS_10StringImplE(void*) { return true; }

// === JSC debug assertion stubs ===

unsigned _ZN3JSC10AssertNoGC19s_scopeReentryCountE = 0;
void _ZN3JSC3DFG11DoesGCCheck11verifyCanGCERNS_2VME(void*) {}

const char* _ZN3JSC14ExceptionScope26unexpectedExceptionMessageEv() {
    return "Unexpected exception (iOS stub)";
}

void _ZN3JSC10ThrowScopeC1ERNS_2VMENS_22ExceptionEventLocationE(void*, void*, ...) {}
void _ZN3JSC10ThrowScopeC2ERNS_2VMENS_22ExceptionEventLocationE(void*, void*, ...) {}
void _ZN3JSC10ThrowScopeD1Ev(void*) {}
void _ZN3JSC10ThrowScopeD2Ev(void*) {}

void _ZN3JSC10ThrowScope14throwExceptionEPNS_14JSGlobalObjectEPNS_9ExceptionE(void*, void*, void*) {
    __builtin_trap();
}
void _ZN3JSC10ThrowScope14throwExceptionEPNS_14JSGlobalObjectENS_7JSValueE(void*, void*, long long) {
    __builtin_trap();
}

void _ZN3JSC17TopExceptionScopeC1ERNS_2VMENS_22ExceptionEventLocationE(void*, void*, ...) {}
void _ZN3JSC17TopExceptionScopeC2ERNS_2VMENS_22ExceptionEventLocationE(void*, void*, ...) {}
void _ZN3JSC17TopExceptionScopeD1Ev(void*) {}
void _ZN3JSC17TopExceptionScopeD2Ev(void*) {}

void _ZN3JSC25ObjectInitializationScopeC1ERNS_2VME(void*, void*) {}
void _ZN3JSC25ObjectInitializationScopeC2ERNS_2VME(void*, void*) {}
void _ZN3JSC25ObjectInitializationScopeD1Ev(void*) {}
void _ZN3JSC25ObjectInitializationScopeD2Ev(void*) {}

bool _ZN3JSC9HandleSet10isLiveNodeEPNS_10HandleNodeE(void*) { return true; }
void _ZN3JSC11MarkedBlock19assertMarksNotStaleEv(void*) {}
void _ZN3JSC12RegExpObject14finishCreationERNS_2VME(void*, void*) {}

static char dummyStrongRefTracker[64];
void* _ZN3JSC16StrongRefTracker19refTrackerSingletonEv() { return dummyStrongRefTracker; }

// === JIT stubs (no JIT on iOS) ===

void* _ZN3JSC3JIT11compileSyncERNS_2VMEPNS_9CodeBlockENS_20JITCompilationEffortE(void*, void*, int) {
    return nullptr;
}
double _ZN3JSC3JIT16totalCompileTimeEv() { return 0; }

void* _ZN3JSC16performJITMemcpyIXtlN3WTF18ConstexprOptionSetINS_14RepatchingFlagEEEEEEEPvS5_PKvm(
    void* dst, const void* src, unsigned long n) {
    return __builtin_memcpy(dst, src, n);
}

// === Zig debug symbol ===

const char* Bun__CallFrame__describeFrame(void* callFrame) { (void)callFrame; return "<frame>"; }

} // extern "C"
